Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - app/controllers/api/soundshare/history_controller.rb
    - app/controllers/api/customer/worker_record_controller.rb

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 120
  Exclude:
    - app/controllers/api/soundshare_controller.rb

AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - assets/**/*
    - lib/tasks/adhoc/*
    - coverage/**/*
    - node_modules/**/*
    - app/inputs/image_preview_input.rb
    - Gemfile
    - spec/**/*
    - config/initializers/*
    - config/routes.rb

Metrics/CyclomaticComplexity:
  Max: 10
